### ISSUE TITLE
Trouble reading the github page for this project

### ISSUE THREAD

**Issue by Computerfan23** [n64decomp/banjo-kazooie#3]
Hi there! I am a visually impaired gamer and i just found out about the decompile project for Banjo Kazooie. I use a screen reader, which is a program to read all text on websites and speak it bak with a text to speech. I have tried to navigate this github page for Banjo Kazooie, but unfortunately, it is not possible. I can't view the progress of the project, like see how much percent is done. All i get is a bunch of links which my screen reader can't do anything with. I get nothing read at all.
So would it be possible to find a way to make the site more easier for me to read using a screen reader?

**Comment by AlxBrx** [comment]
The progress percentage was added as text instead of just svg to the readme a while ago. Does this solve your problem? If so, I would recommend closing this issue as solved.

**Comment by Computerfan23** [comment]
Hi!
Ah, i was not aware of that. I have seen that it was changed. It does solve my problem.
How would i close it? I am not used to how that works.
