### ISSUE TITLE
why has this stalled for so long?

### ISSUE THREAD

**Issue by eddilara** [n64decomp/banjo-kazooie#6]
come on people...only 1.4%

**Comment by theballaam96** [comment]
The last few percent will always be the hardest as it will be the final functions that are tough to get a match without getting regalloc'd.

It's quite rude to say "come on people" like this when decomp projects are people giving up their free time to do this.

The most productive thing to getting this decomp complete would be to set it up on your machine and see whether you can solve some of those functions that have eluded the others.

**Comment by DKRacingFan** [comment]
> come on people...only 1.4%

Stuff like this takes time...  plus the one who's been working on this project the most won't be working on this again till June cause they have been working on moving for awhile and won't access to their pc till then.

**Comment by Lucoshi** [comment]
> The last few percent will always be the hardest as it will be the final functions that are tough to get a match without getting regalloc'd.
> 
> It's quite rude to say "come on people" like this when decomp projects are solely fueled by people giving up their free time to solve 1000+ puzzles.
> 
> The most productive thing to getting this decomp complete would be to set it up on your machine and see whether you can solve some of those functions that have eluded the others.

I totally agree with you!
