### ISSUE TITLE
Hackability

### ISSUE THREAD

**Issue by markusbkk** [n64decomp/banjo-kazooie#7]
I notice that when I make even a small change (such as replacing a piece of text in `src/core2/ch/gameSelect.c`) the resulting ROM no longer functions and **make** complains that it differs from the baserom.

Is this something that will change in the future? IMO, the whole beauty of decompilation is to make changes.

I didn't have much success simply removing the `verify` portion of the Makefile either.

**Comment by RevoSucks** [comment]
Out of scope, not the primary repo
